## Qamar Zia
### Batch 19
### Roll NO :PIAIC139932 
### Assignment 1 : 50 Numpy Functions

In [26]:
%config IPCompleter.greedy=True

In [1]:
import numpy as np

1.SUM

In [2]:
a=[1,2,3,4,5,6]
np.sum(a)

21

2.Substract

In [7]:
b=10
c=20
np.subtract(c,b)

10

3. Multiply

In [8]:
np.multiply(b,c)

200

4. Divide

In [9]:
np.divide(b,c)

0.5

5. MAximum value

In [10]:
np.max(a)

6

6. Minimum value

In [11]:
np.min(a)

1

7. Mean

In [12]:
np.mean(a)

3.5

8.Median

In [13]:
np.median(a)

3.5

9. Sort

In [15]:
d=[4,7,5,3,1,2]
np.sort(d)

array([1, 2, 3, 4, 5, 7])

10. Arrange

In [17]:
f=np.arange(13)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

11. Reshape

In [22]:
np.reshape(f,(1,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

12.Array

In [27]:
x=np.array([[1,2,3],[4,5,6]], np.int32)
type(x)

numpy.ndarray

13.Transpose

In [29]:
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6]])

14.Agrigate

In [40]:
np.argmin(x,1)

array([0, 0], dtype=int64)

15.Complex-conjugate

In [41]:
np.conj(x)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

16.Round

In [42]:
r=[1.2,1.9,2.5,3.8]
np.round(r)

array([1., 2., 2., 4.])

17. cumulative sum

In [44]:
np.cumsum(x)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

18.Variance

In [45]:
np.var(x)

2.9166666666666665

19.Strand Deviation

In [46]:
np.std(x)

1.707825127659933

20.Product

In [47]:
np.prod(x)

720

21.Cumulitative Product

In [48]:
np.cumprod(x)

array([  1,   2,   6,  24, 120, 720], dtype=int32)

22.Evaluation 

In [49]:
np.all(x)

True

23.Copy

In [51]:
ax=np.copy(x)
ax

array([[1, 2, 3],
       [4, 5, 6]])

24.Changing Type

In [53]:
x.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

25. Return diagonals

In [55]:
x.diagonal()

array([1, 5])

26. Fill the array

In [57]:
ax.fill(11)
ax

array([[11, 11, 11],
       [11, 11, 11]])

27.Finding the location of non zero elements

In [58]:
x.nonzero()

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

28.Squeezing the array

In [59]:
x.squeeze()

array([[1, 2, 3],
       [4, 5, 6]])

29.Swaping axis of array

In [64]:
print(x.swapaxes(1,0))
print(x.swapaxes(0,1))


[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


30.Converting to bytes

In [65]:
x.tobytes()

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00'

31.Converting to List

In [66]:
x.tolist()

[[1, 2, 3], [4, 5, 6]]

32.Converting To String

In [70]:
x.tostring()

C:\Users\camar\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  """Entry point for launching an IPython kernel.


b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00'

33.Compress

In [78]:
x.compress([0,1])

array([2])

34.Dot product

In [85]:
a = np.eye(2)
b = np.ones((2, 2)) * 2
a.dot(b)

array([[2., 2.],
       [2., 2.]])

35.Dumping to file

In [91]:
x.dump("D:/text.txt")

36.Peak To Peak Values

In [92]:
x.ptp()

5

37.Putting values in ndarray

In [97]:
x.put([3,5],[8,5])
x

array([[1, 2, 3],
       [8, 4, 5]])

38.Flatened Array

In [98]:
x.ravel()

array([1, 2, 3, 8, 4, 5])

39.Repeat Values

In [103]:
x.repeat(2)

array([1, 1, 2, 2, 3, 3, 8, 8, 4, 4, 5, 5])

40.Get Field values

In [107]:
l=np.eye(3)
l.getfield(np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

41.Set Field Values

In [110]:
l.setfield(4,np.float)
l

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

42.Find shape of Matrix

In [112]:
l.shape

(3, 3)

43.Number of Dimensions

In [113]:
l.ndim

2

44.Seeing the memory location of saved variable

In [116]:
l.data

45.Finding Size of variable

In [117]:
l.size

9

46.Find data type of variable

In [118]:
l.dtype

dtype('float64')

47.Seeing in Real numbers

In [119]:
l.real

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

48.find if value of array are finite

In [125]:
np.isfinite(x)

array([[ True,  True,  True],
       [ True,  True,  True]])

49.Return a matrix with ones on the diagonal and zeros elsewhere.

In [126]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

50. Random Sampling

In [127]:
from numpy import random
random=random.standard_normal(10)
random

array([ 0.28904184, -0.99822008,  1.24185362,  0.50820788, -0.4637133 ,
        0.58233755, -1.24088558, -0.63649171,  0.38211465, -1.22668859])

## Thank You